InternetShop/Controllers/KoszykController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InternetShop.Controllers
{
    public class KoszykController : Controller
    {
        // GET: Koszyk
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult DodajdoKoszyka(string id)
        {
            return View();
        }

    }
}

InternetShop/Controllers/KursyController.cs
using InternetShop.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InternetShop.Controllers
{
    public class KursyController : Controller
    {

        private KursyContext db = new KursyContext();
        // GET: Kursy
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Lista(string nazwaKategori)
        {
            var kategoria = db.Kategorie.Include("Kursy").Where(k => k.NazwaKategorii.ToUpper() == nazwaKategori.ToUpper()).Single();
            var kursy = kategoria.Kursy.ToList();
            return View(kursy);
        }

        public ActionResult Sczegoly(string id)
        {
            var kurs = db.Kursy.Find(id);

            return View(kurs);
        }

        [ChildActionOnly]
        public ActionResult KategorieMenu()
        {

            var kategorie = db.Kategorie.ToList();



            return PartialView("_KategorieMenu",kategorie);
        }

    }
}

InternetShop/Views/Kursy/Lista.cshtml
@{
    ViewBag.Title = "Lista";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div id="ListaKategoriZawartosc">
    @Html.Action("KategorieMenu")
    <div id="KategorieListPrawaSekcja">
        <div id="Breadcrumb">
            <img src="../Content/Images/dommaly.png" />
            <a href="link">
                Start > ASP.NET
            </a>
        </div>

        <div id="SekcjaListaKategori">
            @Html.Partial("_KursyList")
        </div>

    </div>
</div>

InternetShop/Views/Kursy/Sczegoly.cshtml
@model InternetShop.Models.Kurs
    @using InternetShop.Infrastructure

@{
    ViewBag.Title = "Sczegoly";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div id="ListaKategoriZawartosc">
   @Html.Action("KategorieMenu")
    <div id="KategorieListPrawaSekcja">
        <div id="Breadcrumb">
            <img src="../Content/Images/dommaly.png" />
            <a href="link">
                Start > ASP.NET
            </a>
        </div>
        <section id="SekcjaKurs">
            <div id="KursLewa">
                <img src="@Url.ObrazkiSciezka(Model.NazwaPlikuObrazka)" />
            </div>
            <div id="KursPrawa">
                <div id="KursNazwa">
                    <h1>
                        @Model.TytulKursu
                    </h1>
                    <h2>
                        @Model.AutorKursu
                    </h2>
                </div>
                <div id="KursCena">
                    <div>
                        @string.Format("{0:0.##",Model.CenaKursu)<span>PLN</span>
                    </div>
                    <a href="@Url.Action("DodajDoKoszyka","Koszyk", new { id = Model.KursId })"></a>
                </div>
                <div id="KursOpis">
                    @Model.OpisKursu
                </div>
                <div id="KursInfo">
                    @Model.OpisSkrocony
                </div>

            </div>
        </section>
    </div>
</div>

InternetShop/Views/Kursy/_KategorieMenu.cshtml
@model IEnumerable<InternetShop.Models.Kategoria>
    @using InternetShop.Infrastructure

<nav class="KategorieVertical">
    <ul>
        @foreach(var kategoria in Model)
        {
        <li>
            <a href="@Url.Action("Lista","Kursy", new {nazwaKategori= kategoria.NazwaKategorii.ToString()})"
                style="background-image: url(@Url.IkonyKategoriiSciezka(kategoria.NazwaPlikuIkony); ">
                @kategoria.NazwaKategorii
            </a>
        </li>
        }
    </ul>
</nav>

InternetShop/Views/Kursy/_KursyList.cshtml
@model IEnumerable<InternetShop.Models.Kurs>
    @using InternetShop.Infrastructure


<div id="SekcjaListaKategori">
    <ul class="KursyTrzyKolumny MalaListaKategorii">
        @foreach (var kurs in Model)
        {
            <li>
                <article>
                    <a class="dodajDoKoszykaLink" href="@Url.Action("DodajdoKoszyka","Koszyk", new { id = kurs.KursId })">
                        <img src="@Url.Content("~/Content/Images/koszyk.png")" />
                    </a>
                    @if (kurs.Bestsseller)
                    {
                        <div class="bestsellerFlag"></div>
                    }


                    <a class="kursSzczegolyLink" href="@Url.Action("Szczegoly","Kursy", new { id = kurs.KursId })">
                        <img class="kurs" src="@Url.ObrazkiSciezka(kurs.NazwaPlikuObrazka)" />
                        <h1>
                            @kurs.AutorKursu -  @kurs.TytulKursu
                        </h1>
                    </a>
                </article>
            </li>
        }
    </ul>
</div>